# Generated by Django 5.1.3 on 2024-11-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('sijainti', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Varaaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('yhteystiedot', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Varaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alku_aika', models.DateTimeField()),
                ('loppu_aika', models.DateTimeField()),
                ('tila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varaukset', to='api.tila')),
                ('varaaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varaukset', to='api.varaaja')),
            ],
        ),
    ]
